Bonjour,

after a long time without Pythojn, I loaded Python 262.
IDLE is refusing to start, claiming there is a personnal firewall Protection  hindering subprocesses.
I'm on Win XP.
What should I do?

Thanks on forward
